Parse author & tab and handle `l()` translation function
loveOSS/psssst pull request #8
Opened 2022-03-11 16:18 UTC by atomiix

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This PR aims to return the author & tab of a module being parsed along with the other info already returned. It Also get the string of the `l()` function the same way it does with the `trans()` function.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | Try `./psssst /directory/of/a/module/` and check that the author and tab are returned.
| Possible impacts? |

2022-03-11 16:30 UTC, matks requested changes

2022-03-12 21:27 UTC, matks approved these changes

2022-03-12 21:28 UTC, matks commented
@atomiix QA by dev I guess ? 😉

2022-03-14 08:50 UTC, atomiix commented
@matks easier for a dev indeed!

2022-03-14 09:20 UTC, PierreRambaud approved these changes

2022-03-18 14:49 UTC, matks commented
Tested by me

### Optimal case

Valid

### Use of variables

Not supported but no error
![Capture d’écran 2022-03-18 à 15 45 23](https://user-images.githubusercontent.com/3830050/159025431-a6eaaa62-8cf0-4c70-b66b-78ed1c77ebe7.png)
![Capture d’écran 2022-03-18 à 15 45 23](https://user-images.githubusercontent.com/3830050/159025431-a6eaaa62-8cf0-4c70-b66b-78ed1c77ebe7.png)

### Use of translated string

Not supported and error is printed b
![Capture d’écran 2022-03-18 à 15 46 50](https://user-images.githubusercontent.com/3830050/159025519-152f405d-2b99-4cb1-b462-4a6084d743a3.png)
![Capture d’écran 2022-03-18 à 15 46 50](https://user-images.githubusercontent.com/3830050/159025519-152f405d-2b99-4cb1-b462-4a6084d743a3.png)
ut no crash

2022-03-18 14:49 UTC, matks commented
Tested by me

### Optimal case

Valid

### Use of variables

Not supported but no error
![Capture d’écran 2022-03-18 à 15 45 23](https://user-images.githubusercontent.com/3830050/159025431-a6eaaa62-8cf0-4c70-b66b-78ed1c77ebe7.png)
![Capture d’écran 2022-03-18 à 15 45 23](https://user-images.githubusercontent.com/3830050/159025431-a6eaaa62-8cf0-4c70-b66b-78ed1c77ebe7.png)

### Use of translated string

Not supported and error is printed b
![Capture d’écran 2022-03-18 à 15 46 50](https://user-images.githubusercontent.com/3830050/159025519-152f405d-2b99-4cb1-b462-4a6084d743a3.png)
![Capture d’écran 2022-03-18 à 15 46 50](https://user-images.githubusercontent.com/3830050/159025519-152f405d-2b99-4cb1-b462-4a6084d743a3.png)
ut no crash

2022-03-18 14:50 UTC, matks approved these changes
Merged because expected behavior is correct

2022-03-18 14:50 UTC, merged